name: 'Jekyll Actions'
description: 'A GitHub Action to build and publish Jekyll sites to GitHub Pages'
inputs:
  token:
    description: 'The GITHUB_TOKEN secret'
    required: false
  jekyll_env:
    description: 'The Jekyll environment to build'
    required: false
  jekyll_src:  
    description: 'The Jekyll website source directory'
    required: false
  jekyll_build_options:  
    description: 'Additional Jekyll build arguments (see https://jekyllrb.com/docs/configuration/options/#build-command-options)'
    required: false
  gem_src:
    description: 'The Jekyll Gemfile directory'
    required: false
  target_branch:
    description: 'The target branch name the site gets pushed to'
    required: false
  target_path:
    description: 'The relative path where the site gets pushed to'
    required: false
  build_only:
    description: 'Will build the Jekyll site without publishing it'
    required: false
  keep_history:
    description: 'Do not overwrite whatever was already published on the target branch'
    required: false
  pre_build_commands:
    description: >
      Commands to run prior to build and deploy. Useful for
      ensuring build dependencies are up to date or installing 
      new dependencies. For example, use `apk --update add 
      imagemagick` to install ImageMagick.
    required: false
outputs:
  sha: 
    description: 'Generated commit SHA1 that will be published'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'book'
  color: 'blue'
